issue-11 駒を移動できる
serviver-agent/shogi-api-server pull request #12
Opened 2020-09-22 10:14 UTC by KazuyaMiyashita

fix #11

2020-09-22 10:19 UTC, KazuyaMiyashita commented
次issue候補: 

* `moveKoma(from: Area, to: Area, player: Player)` だけではひよこが成るかどうかを指定できない
* `Area` と `RelativeArea` のy座標の向きが逆なのを揃える？

2020-09-22 10:21 UTC, KazuyaMiyashita commented
* `Komadai` には `Seq[Koma]` があるが、 `Koma` には `Player` があるため、 `senteKomadai = Komadai(Sente, Seq(Hiyoko(Gote)))` のような不要な情報が含まれてしまう

2020-09-22 19:08 UTC, YuMuuu requested changes

2020-09-22 19:08 UTC, YuMuuu commented on src/main/scala/core/Area.scala
> +  * 先手番から見たマスの座標を表す
Areaはチェスの代数式のようなもので盤面の左上を基点にし横をアルファベット、縦を算用数字にしたものに対応する絶対的な座標です。
Areaの座標は絶対的なものなのでplayerによって座標が変わる事はありません
確かに`マスの座標を表す`だけだとどこか基点なのかわからないので
```
どうぶつしょうぎの盤のマスの座標を表す
盤面の左上を起点とし横軸をx、縦軸をとする。
```
のようにするのはどうでしょう？

2020-09-22 19:08 UTC, YuMuuu commented on src/main/scala/core/Area.scala
> +    val nextY = y - relativeArea.y // FIXME: Areaのyは下向きが正だが、RelativeAreaのyは上向きが正である
Areaに合わせてリファクタリングをお願いします

2020-09-22 19:08 UTC, YuMuuu commented on src/main/scala/core/Area.scala
> +  * 先手番から見た駒が動ける相対位置を表している
先手番からではなく駒のowner(player)からみた駒が動ける相対位置を表しているものです。

2020-09-22 19:08 UTC, YuMuuu commented on src/main/scala/core/Board.scala
> +    masus: Set[Masu],
good

2020-09-22 19:08 UTC, YuMuuu commented on src/main/scala/core/Board.scala
> +  def moveKoma(from: Area, to: Area, player: Player): Either[MoveKomaError, Board] = {
これだと駒台から駒をマスに打つ事が表せていない

2020-09-22 19:17 UTC, KazuyaMiyashita commented on src/main/scala/core/Area.scala
> +  * 先手番から見たマスの座標を表す
質問ですが、AreaのA1は必ず先手番から見た左上のマスの座標だということは正しいですか？

2020-09-22 19:20 UTC, KazuyaMiyashita commented on src/main/scala/core/Area.scala
> +  * 先手番から見た駒が動ける相対位置を表している
そのようにすると、AreaとRelativeAreaの加算にPlayerの情報が必要になってしまいやや複雑になります。

2020-09-22 19:35 UTC, YuMuuu commented on src/main/scala/core/Area.scala
> +  * 先手番から見たマスの座標を表す
正しいです

2020-09-22 19:37 UTC, YuMuuu commented on src/main/scala/core/Area.scala
> +  * 先手番から見た駒が動ける相対位置を表している
変更後の説明だと先手が`後手がowner`の駒を見たときに駒の動きが先手がownerの時の動きになりませんか？
（先手と先手番で指しているものが違ったりしますか？）

2020-09-22 19:42 UTC, KazuyaMiyashita commented on src/main/scala/core/Area.scala
> +  * 先手番から見たマスの座標を表す
では、
「盤面の座標は先手番の視点で左上をA1とし、横軸をx（右に正）、縦軸をy（下に正）とする」
はどうでしょうか？

2020-09-22 19:49 UTC, YuMuuu commented on src/main/scala/core/Area.scala
> +  * 先手番から見たマスの座標を表す
それでいきましょう

2020-09-22 19:57 UTC, KazuyaMiyashita commented on src/main/scala/core/Area.scala
> +  * 先手番から見た駒が動ける相対位置を表している
（先手と先手番は同じものを指しています）

先手から見て、先手のひよこは盤面の奥に進み、後手のひよこは盤面の手前に動きます。(1)
一方で、ひよこは必ず向いている方向に（=持っているプレイヤーの目線で）前に進みます。(2)

(1)は盤面の座標の計算で利用する、向きが固定された相対座標で、(2)は駒が進むことが可能な場所を示す相対座標で、向きは固定されません。

現在のモデリングだと(1)と(2)を同じRelativeAreaを用いて実装しているため、齟齬が生じる状態になっています。
（RelativeAreaにseenFromを生やして向きを反転させています。）

よりよいモデリングの案としては、RelativeAreaは(1)の意味で用いて、KomaのrelativeAreaをprivateにし、KomaにPlayer => RelativeAreaを定義するのが良さそうです。

でも面倒くさくてこのPRではやってません。

2020-09-22 20:22 UTC, YuMuuu commented on src/main/scala/core/Area.scala
> +  * 先手番から見た駒が動ける相対位置を表している
実装の話ではなく説明が正しくないという話をしています。

(2)の利用を想定して作ったmodelで元々の説明にも`駒が動ける相対位置を表している`と書いてあります。
seenFromで(1)を表現できているので実装は（リファクタリングする余地はあったとしてもとりあえずは）問題ないと考えます。

RelativeAreaは(2)を表現しているものなので、「`先手番`から見た駒が動ける相対位置を表している」の`手番`の情報は要らないです。
駒の動きは駒の種類とowner(駒の持ち主)によって決まるのでそのまま`RelativeAreaは駒が動ける相対位置を表している`の説明で問題ないと思います。

2020-09-22 20:27 UTC, KazuyaMiyashita commented on src/main/scala/core/Area.scala
> +  * 先手番から見た駒が動ける相対位置を表している
別途issue立てるのでヨロ

2020-09-23 13:49 UTC, KazuyaMiyashita commented on src/main/scala/core/Area.scala
> +  * 先手番から見たマスの座標を表す
修正した！

2020-09-23 13:49 UTC, KazuyaMiyashita commented on src/main/scala/core/Area.scala
> +    val nextY = y - relativeArea.y // FIXME: Areaのyは下向きが正だが、RelativeAreaのyは上向きが正である
修正した！

2020-09-23 13:50 UTC, KazuyaMiyashita commented on src/main/scala/core/Area.scala
> +  * 先手番から見た駒が動ける相対位置を表している
RelativeAreaの意味を変えてしまった！あとは好きにしろ！

2020-09-23 13:50 UTC, merged